### ISSUE TITLE
some boilerplate code left

### ISSUE THREAD

**Issue by jeznag** [caretgrowth/zoho-grid-widget-vue#3]
https://github.com/caretgrowth/zoho-grid-widget-vue/blob/master/src/store/index.js#L17

stargazers etc. doesn't seem relevant

**Comment by mikesimps** [comment]
Hey @jeznag honestly this is just an example for others to learn from or extend themselves. Is there something about that field that takes away from the example? What would be more relevant to include?

**Comment by jeznag** [comment]
Might be more intuitive if it had columns like Lead Name, Lead Source etc.

Agree not a big deal. Thanks for open sourcing!
